spring.application.name=user
spring.datasource.url=jdbc:mysql://localhost:3306/userDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=US0726unaiz@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
app.jwt.secret=up07052002p34f1e600cd89b424cbb63
app.jwt.expiration=3600000